### ISSUE TITLE
Maybe change to Snowpack?

### ISSUE THREAD

**Issue by jwanner83** [faragos/lfr-js-portlet-utils#1]
I'm not an expert in this segment but maybe snowpack would be a great alternative to use instead of webpack because of great performance.

https://www.snowpack.dev/posts/2020-05-26-snowpack-2-0-release/

**Comment by faragos** [comment]
At the moment it looks like Liferay will move to Webpack so it would be best to stay with the same technology. Also I have no experience with snowpack, the online community isn't as big as it is with Webpack and I don't think Webpack is too slow at the moment. And if you compare it with normal Liferay deploy it's enough fast IMO. But thank you for your input 👍
